
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/readingroom?severTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : tjsqja97

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true